
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/app/component/Header";
import Services from "@/app/component/Services";
import Home from "@/app/component/Home";
import Testimonials from "@/app/component/Testimonials";
import Contact from "@/app/component/Contact";
import CaseStudies from "./component/CaseStudies";
import WorkingProcess from "./component/WorkingProcess";
import Teams from "./component/Teams";
import Footer from "./component/Footer";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* header */}
    <Header/>
    {/* main content */}
    <main>
    <Home />
        <Services />
        <CaseStudies/>
        <WorkingProcess/>
        <Teams/>
        <Testimonials />
        <Contact />
    </main>
    {/* footer */}
    <Footer/>
        {children}
      </body>
    </html>
  );
}
